USE master;

IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N'BOSS_SCHOOLS_SHARED_SNAPSHOT')
DROP DATABASE BOSS_SCHOOLS_SHARED_SNAPSHOT

CREATE DATABASE BOSS_SCHOOLS_SHARED_SNAPSHOT ON
( 
    NAME = BOSS_SCHOOLS_SHARED, 
    FILENAME = '{0}\BOSS_SCHOOLS_SHARED_SNAPSHOT.ss' 
)
AS SNAPSHOT OF BOSS_SCHOOLS_SHARED;