//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumWebDriver.Examples {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DatabaseQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatabaseQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeleniumWebDriver.Examples.DatabaseQueries", typeof(DatabaseQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE master;
        ///
        ///IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N&apos;BOSS_SCHOOLS_SHARED_SNAPSHOT&apos;)
        ///DROP DATABASE BOSS_SCHOOLS_SHARED_SNAPSHOT
        ///
        ///CREATE DATABASE BOSS_SCHOOLS_SHARED_SNAPSHOT ON
        ///( 
        ///    NAME = BOSS_SCHOOLS_SHARED, 
        ///    FILENAME = &apos;{0}\BOSS_SCHOOLS_SHARED_SNAPSHOT.ss&apos; 
        ///)
        ///AS SNAPSHOT OF BOSS_SCHOOLS_SHARED;.
        /// </summary>
        internal static string CreateSnapshot {
            get {
                return ResourceManager.GetString("CreateSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N&apos;BOSS_SCHOOLS_SHARED_SNAPSHOT&apos;)
        ///DROP DATABASE BOSS_SCHOOLS_SHARED_SNAPSHOT.
        /// </summary>
        internal static string DropSnapshot {
            get {
                return ResourceManager.GetString("DropSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE master;
        ///RESTORE DATABASE BOSS_SCHOOLS_SHARED from 
        ///DATABASE_SNAPSHOT = &apos;BOSS_SCHOOLS_SHARED_SNAPSHOT&apos;;.
        /// </summary>
        internal static string RestoreSnapshot {
            get {
                return ResourceManager.GetString("RestoreSnapshot", resourceCulture);
            }
        }
    }
}
